<?php
/**
 * Per-language URLs (/en/page/): rewrite rules and active language detection.
 *
 * Always loaded (admin and front end) so any rewrite rules regeneration —
 * for example when saving Settings → Permalinks — includes the
 * language-prefixed variants.
 */

defined( 'ABSPATH' ) || exit;

class Locuentia_Router {

	const FLUSH_FLAG = 'locuentia_flush_rewrite';

	/**
	 * While true, the permalink filters do not apply any language
	 * (allows retrieving the original URL of a post).
	 *
	 * @var bool
	 */
	private static $suspended = false;

	public static function init() {
		add_filter( 'rewrite_rules_array', array( __CLASS__, 'add_language_rules' ) );
		add_filter( 'query_vars', array( __CLASS__, 'register_query_var' ) );
		add_action( 'init', array( __CLASS__, 'maybe_flush' ), 20 );

		// Language home pages with a static front page: core only maps an
		// "empty" query to page_on_front when it has no extra vars, and
		// locuentia_lang counts as one, so /en/ would fall back to the posts
		// list. Resolved here instead (priority 9, before slug resolution).
		add_filter( 'request', array( __CLASS__, 'resolve_front_page' ), 9 );

		// Resolution of translated slugs on the incoming request.
		add_filter( 'request', array( __CLASS__, 'resolve_translated_slug' ) );

		// Outgoing URLs: with an active language, internal links carry the
		// prefix and the translated slug. In the admin there is no active
		// language, so these filters change nothing there.
		add_filter( 'page_link', array( __CLASS__, 'localize_post_url' ), 10, 2 );
		add_filter( 'post_link', array( __CLASS__, 'localize_post_url' ), 10, 2 );
		add_filter( 'post_type_link', array( __CLASS__, 'localize_post_url' ), 10, 2 );
		add_filter( 'term_link', array( __CLASS__, 'localize_plain_url' ) );

		// WordPress canonical redirects do not know about the prefix and
		// would kick the visitor out of the language (e.g. /en/ → /);
		// we put it back.
		add_filter( 'redirect_canonical', array( __CLASS__, 'localize_canonical' ), 10, 2 );

		// Core considers the URL with the real slug canonical, so the
		// redirect to the translated slug (/en/original-slug/ →
		// /en/translated-slug/) has to happen here.
		add_action( 'template_redirect', array( __CLASS__, 'redirect_untranslated_slug' ) );
		add_action( 'add_option_' . Locuentia::OPTION_LANGUAGES, array( __CLASS__, 'schedule_flush' ) );
		add_action( 'update_option_' . Locuentia::OPTION_LANGUAGES, array( __CLASS__, 'schedule_flush' ) );
		add_action( 'add_option_' . Locuentia::OPTION_SOURCE, array( __CLASS__, 'schedule_flush' ) );
		add_action( 'update_option_' . Locuentia::OPTION_SOURCE, array( __CLASS__, 'schedule_flush' ) );
	}

	/**
	 * Active language of the request: /xx/ URL prefix or ?locuentia_lang=xx.
	 *
	 * @return string Language code, or '' for the original text.
	 */
	public static function current_language() {
		static $cached = null;

		if ( null !== $cached ) {
			return $cached;
		}

		$cached = '';

		$languages = Locuentia::get_languages();
		if ( empty( $languages ) ) {
			return $cached;
		}

		if ( isset( $_SERVER['REQUEST_URI'] ) ) {
			$request_uri = esc_url_raw( wp_unslash( $_SERVER['REQUEST_URI'] ) );
			$path        = (string) wp_parse_url( $request_uri, PHP_URL_PATH );
			$home_path   = (string) wp_parse_url( home_url( '/' ), PHP_URL_PATH );

			if ( '' !== $home_path && 0 === strpos( $path, $home_path ) ) {
				$path = substr( $path, strlen( $home_path ) );
			}

			$segment = strtok( ltrim( $path, '/' ), '/' );
			if ( false !== $segment && in_array( $segment, $languages, true ) ) {
				$cached = $segment;
				return $cached;
			}
		}

		// ?locuentia_lang=xx fallback. Public read: it only picks the displayed language.
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended
		if ( isset( $_GET['locuentia_lang'] ) && is_string( $_GET['locuentia_lang'] ) ) {
			// phpcs:ignore WordPress.Security.NonceVerification.Recommended
			$requested = Locuentia::sanitize_language_code( sanitize_key( wp_unslash( $_GET['locuentia_lang'] ) ) );
			if ( '' !== $requested && in_array( $requested, $languages, true ) ) {
				$cached = $requested;
			}
		}

		return $cached;
	}

	/**
	 * Duplicates every rewrite rule under the language prefix: (en|fr)/…
	 *
	 * The language group becomes $matches[1], so the indexes of the original
	 * query shift by one.
	 *
	 * @param array $rules Rules generated by WordPress.
	 * @return array
	 */
	public static function add_language_rules( $rules ) {
		if ( ! is_array( $rules ) || empty( $rules ) ) {
			return $rules;
		}

		$languages = Locuentia::get_languages();
		if ( empty( $languages ) ) {
			return $rules;
		}

		$quoted = array();
		foreach ( $languages as $code ) {
			$quoted[] = preg_quote( $code, '#' );
		}
		$group = '(' . implode( '|', $quoted ) . ')';

		$localized = array(
			// Home page of each language: /en/
			$group . '/?$' => 'index.php?locuentia_lang=$matches[1]',
		);

		foreach ( $rules as $regex => $query ) {
			$shifted = preg_replace_callback(
				'/\$matches\[(\d+)\]/',
				function ( $m ) {
					return '$matches[' . ( (int) $m[1] + 1 ) . ']';
				},
				$query
			);

			$localized[ $group . '/' . ltrim( $regex, '^' ) ] = $shifted . '&locuentia_lang=$matches[1]';
		}

		return $localized + $rules;
	}

	/**
	 * Registers locuentia_lang as a public query var.
	 *
	 * @param array $vars Query vars.
	 * @return array
	 */
	public static function register_query_var( $vars ) {
		$vars[] = 'locuentia_lang';
		return $vars;
	}

	/**
	 * Flags that the rules must be regenerated on the next load.
	 */
	public static function schedule_flush() {
		update_option( self::FLUSH_FLAG, 1 );
	}

	/**
	 * Regenerates the rules when pending (after activation or language changes).
	 */
	public static function maybe_flush() {
		if ( get_option( self::FLUSH_FLAG ) ) {
			delete_option( self::FLUSH_FLAG );
			flush_rewrite_rules();
		}
	}

	/**
	 * Returns the URL pointing to a given language version.
	 *
	 * With pretty permalinks it inserts the prefix (/en/…); without them it
	 * falls back to ?locuentia_lang=xx. Idempotent: if the URL already
	 * carries a language, it is swapped.
	 *
	 * @param string $url  Absolute URL within the site.
	 * @param string $lang Target language code.
	 * @return string
	 */
	public static function localize_url( $url, $lang ) {
		$lang = Locuentia::sanitize_language_code( $lang );
		if ( '' === $lang || ! in_array( $lang, Locuentia::get_languages(), true ) ) {
			return $url;
		}

		if ( ! get_option( 'permalink_structure' ) ) {
			return add_query_arg( 'locuentia_lang', $lang, $url );
		}

		$home = home_url( '/' );
		if ( 0 !== strpos( $url, $home ) ) {
			return $url;
		}

		$relative = self::strip_language_prefix( substr( $url, strlen( $home ) ) );

		return $home . $lang . '/' . ltrim( $relative, '/' );
	}

	/**
	 * Maps the language home page (/en/) to the static front page when one
	 * is configured, mirroring the core "empty query → page_on_front" logic
	 * that our language query var would otherwise prevent.
	 *
	 * @param array $query_vars Query vars parsed from the URL.
	 * @return array
	 */
	public static function resolve_front_page( $query_vars ) {
		if ( ! is_array( $query_vars ) || '' === self::current_language() ) {
			return $query_vars;
		}

		if ( 'page' !== get_option( 'show_on_front' ) ) {
			return $query_vars;
		}

		$front_id = (int) get_option( 'page_on_front' );
		if ( ! $front_id ) {
			return $query_vars;
		}

		// Mirror core: the query must be empty apart from our language var
		// and the pagination/preview vars core also ignores.
		$check = $query_vars;
		if ( isset( $check['pagename'] ) && '' === $check['pagename'] ) {
			unset( $check['pagename'] );
		}
		unset( $check['embed'], $check['locuentia_lang'] );

		if ( ! empty( $check ) && array_diff( array_keys( $check ), array( 'preview', 'page', 'paged', 'cpage' ) ) ) {
			return $query_vars;
		}

		$query_vars['page_id'] = $front_id;

		return $query_vars;
	}

	/**
	 * Resolves translated slugs on the request: /en/about-us/ loads the post
	 * whose translated slug in "en" is "about-us".
	 *
	 * @param array $query_vars Query vars parsed from the URL.
	 * @return array
	 */
	public static function resolve_translated_slug( $query_vars ) {
		$lang = self::current_language();
		if ( '' === $lang || ! is_array( $query_vars ) ) {
			return $query_vars;
		}

		$requested = '';
		if ( ! empty( $query_vars['pagename'] ) && is_string( $query_vars['pagename'] ) ) {
			// On hierarchical pages (parent/child) only the own slug is translated.
			$parts     = explode( '/', trim( $query_vars['pagename'], '/' ) );
			$requested = (string) end( $parts );
		} elseif ( ! empty( $query_vars['name'] ) && is_string( $query_vars['name'] ) ) {
			$requested = $query_vars['name'];
		}

		if ( '' === $requested ) {
			return $query_vars;
		}

		$found = get_posts(
			array(
				'post_type'      => Locuentia::post_types(),
				'post_status'    => 'publish',
				'posts_per_page' => 1,
				// Targeted lookup on an indexed key, capped at 1 result.
				'meta_key'       => Locuentia::SLUG_META_PREFIX . $lang, // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_key
				'meta_value'     => $requested, // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_value
				'no_found_rows'  => true,
			)
		);

		if ( empty( $found ) ) {
			return $query_vars;
		}

		$post = $found[0];

		unset( $query_vars['pagename'], $query_vars['name'] );

		if ( 'page' === $post->post_type ) {
			$query_vars['page_id'] = $post->ID;
		} else {
			$query_vars['p'] = $post->ID;
			if ( 'post' !== $post->post_type ) {
				$query_vars['post_type'] = $post->post_type;
			}
		}

		return $query_vars;
	}

	/**
	 * 301-redirects the URL with the original slug under a language prefix
	 * to the URL with the translated slug: /en/original/ → /en/translated/.
	 */
	public static function redirect_untranslated_slug() {
		$lang = self::current_language();
		if ( '' === $lang || ! is_singular( Locuentia::post_types() ) ) {
			return;
		}

		$post = get_queried_object();
		if ( ! $post instanceof WP_Post || '' === (string) $post->post_name ) {
			return;
		}

		$translated = Locuentia::get_translated_slug( $post->ID, $lang );
		if ( '' === $translated || $translated === $post->post_name ) {
			return;
		}

		if ( ! isset( $_SERVER['REQUEST_URI'] ) || ! is_string( $_SERVER['REQUEST_URI'] ) ) {
			return;
		}

		$request_uri  = esc_url_raw( wp_unslash( $_SERVER['REQUEST_URI'] ) );
		$request_path = (string) wp_parse_url( $request_uri, PHP_URL_PATH );

		// Replace the original slug segment while keeping whatever follows
		// (pagination, feed…). If absent, the URL already uses the
		// translated slug.
		$new_path = preg_replace(
			'#/' . preg_quote( $post->post_name, '#' ) . '(/|$)#',
			'/' . $translated . '$1',
			$request_path,
			1
		);

		if ( null === $new_path || $new_path === $request_path ) {
			return;
		}

		$query  = (string) wp_parse_url( $request_uri, PHP_URL_QUERY );
		$target = $new_path . ( '' !== $query ? '?' . $query : '' );

		wp_safe_redirect( $target, 301 );
		exit;
	}

	/**
	 * Original permalink of a post (no prefix, no translated slug).
	 *
	 * @param int|WP_Post $post Post.
	 * @return string
	 */
	public static function unlocalized_permalink( $post ) {
		self::$suspended = true;
		$url             = get_permalink( $post );
		self::$suspended = false;

		return $url ? $url : '';
	}

	/**
	 * Permalink of a post in a language (prefix + translated slug if any).
	 * With an empty $lang it returns the original permalink.
	 *
	 * @param int|WP_Post $post Post.
	 * @param string      $lang Language code or ''.
	 * @return string
	 */
	public static function permalink_for_language( $post, $lang ) {
		$post = get_post( $post );
		if ( ! $post ) {
			return '';
		}

		$url = self::unlocalized_permalink( $post );
		if ( '' === $lang || '' === $url ) {
			return $url;
		}

		return self::swap_slug( self::localize_url( $url, $lang ), $post, $lang );
	}

	/**
	 * page_link/post_link/post_type_link filter: applies the active language
	 * (prefix + translated slug).
	 *
	 * @param string      $url  Original permalink.
	 * @param int|WP_Post $post Post of the link (depending on the filter).
	 * @return string
	 */
	public static function localize_post_url( $url, $post ) {
		if ( self::$suspended ) {
			return $url;
		}

		$lang = self::current_language();
		if ( '' === $lang ) {
			return $url;
		}

		return self::swap_slug( self::localize_url( $url, $lang ), get_post( $post ), $lang );
	}

	/**
	 * term_link filter: with an active language only the prefix is added.
	 *
	 * @param string $url Term URL.
	 * @return string
	 */
	public static function localize_plain_url( $url ) {
		if ( self::$suspended ) {
			return $url;
		}

		$lang = self::current_language();

		return '' === $lang ? $url : self::localize_url( $url, $lang );
	}

	/**
	 * Keeps the language prefix on canonical redirects.
	 *
	 * @param string|false $redirect_url  Proposed canonical URL.
	 * @param string       $requested_url Requested URL.
	 * @return string|false
	 */
	public static function localize_canonical( $redirect_url, $requested_url ) {
		$lang = self::current_language();
		if ( '' === $lang || ! $redirect_url ) {
			return $redirect_url;
		}

		return self::localize_url( $redirect_url, $lang );
	}

	/**
	 * Replaces the last URL segment (the post slug) with its translated
	 * version, if there is one.
	 *
	 * @param string       $url  URL already carrying the language prefix.
	 * @param WP_Post|null $post Post the URL belongs to.
	 * @param string       $lang Language code.
	 * @return string
	 */
	private static function swap_slug( $url, $post, $lang ) {
		if ( ! $post instanceof WP_Post || '' === (string) $post->post_name ) {
			return $url;
		}

		$translated = Locuentia::get_translated_slug( $post->ID, $lang );
		if ( '' === $translated || $translated === $post->post_name ) {
			return $url;
		}

		return preg_replace(
			'#/' . preg_quote( $post->post_name, '#' ) . '(/?)$#',
			'/' . $translated . '$1',
			$url
		);
	}

	/**
	 * URL of the current request without the language prefix (original version).
	 *
	 * @param bool $keep_query Keep the query string (minus the language parameter).
	 * @return string
	 */
	public static function current_url_unlocalized( $keep_query = true ) {
		$request = isset( $_SERVER['REQUEST_URI'] ) && is_string( $_SERVER['REQUEST_URI'] )
			? esc_url_raw( wp_unslash( $_SERVER['REQUEST_URI'] ) )
			: '/';

		$request = remove_query_arg( 'locuentia_lang', $request );

		if ( ! $keep_query ) {
			$request = (string) wp_parse_url( $request, PHP_URL_PATH );
		}

		$home_path = (string) wp_parse_url( home_url( '/' ), PHP_URL_PATH );
		if ( '' !== $home_path && 0 === strpos( $request, $home_path ) ) {
			$request = substr( $request, strlen( $home_path ) );
		}

		return home_url( '/' . self::strip_language_prefix( ltrim( $request, '/' ) ) );
	}

	/**
	 * Strips a leading language prefix from a home-relative path.
	 *
	 * @param string $relative Relative path, e.g. "en/page/".
	 * @return string
	 */
	public static function strip_language_prefix( $relative ) {
		$relative = (string) $relative;

		foreach ( Locuentia::get_languages() as $code ) {
			if ( $relative === $code || $relative === $code . '/' ) {
				return '';
			}
			if ( 0 === strpos( $relative, $code . '/' ) ) {
				return substr( $relative, strlen( $code ) + 1 );
			}
			if ( 0 === strpos( $relative, $code . '?' ) ) {
				return substr( $relative, strlen( $code ) );
			}
		}

		return $relative;
	}
}
